### ISSUE TITLE
Добавить логирование

### ISSUE THREAD

**Issue by kamuz** [bezumkin/debugParser#5]
На странице - https://modx.pro/development/556-the-fastest-snippets-with-pdotools/ увидел что раньше была возможность отслеживать логи через `pdoTools::getTime()`. Можно ли это внести в функционал debugParser и добавить возможность вывода логов не только для pdoTools но и для всего MODX в целом?.

![image](https://file.modx.pro/files/2/8/f/5/8f523271dcf897563eff9b38311403d0.png)

Таким образом будет более понятно как запускается и выдает результат MODX и позволит разрабатывать быстрые сайты.

**Comment by bezumkin** [comment]
Это не раньше, это всегда было и никуда не пропадало.

Встроить в другие места это нельзя, потому что всё работает за счёт вызова функций pdoTools. Если другие сущности их не вызывают - ничего в лог pdoTools и не попадёт.
